# Site settings
title: MQD use Jekyll on Netlify
email: admin@minhquydesign.comn
description: > # this means to ignore newlines until "baseurl:"
  Personal BLOG.
baseurl: "q" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: minhquydesign
github_username:  minhquydesign

# Build settings
markdown: kramdown
